Update to Python 3.11
python/python-docs-zh-cn pull request #301
Opened 2023-02-27 10:51 UTC by BlueGlassBlock

Resolves #289

2023-02-27 10:52 UTC, BlueGlassBlock commented
这个 PR 用 `transifex/cli` 替代了已经停止维护的 `transifex-client`。

2023-02-27 11:30 UTC, WendaoLee approved these changes

2023-02-27 12:57 UTC, BlueGlassBlock commented
`tx pull -f` 对于一个版本只需要几分钟，而且这是默认的 5 并发数。

我发现我重构的配置迁移脚本有些 bug，先 draft 修几天

2023-03-01 04:48 UTC, BlueGlassBlock commented
通过 [Transifex API](https://developers.transifex.com/reference/get_resource-translations) 可以定位有问题的翻译字符串以及贡献这些有语法错误的译者。

2023-03-01 06:12 UTC, ProgramRipper commented
> 根据 `sphinx-lint` 的结果，当下文档里有 1346 个 reStructuredText 语法问题。我准备用脚本批量解决一些特征明显的问题。

我已经将更改上传到 transifex，我已经可以在本地手动构建文档了。

在修复过程中，我发现了大量机翻、明显不懂 reStructuredText 语法和错误翻译。

我认为文档翻译亟待复核。

2023-03-07 05:21 UTC, BlueGlassBlock commented
经过 @ProgramRipper 修复的 3.7 与 3.11 文档已经可以在我的 fork 构建，我认为这个 PR 可以合并了

2023-04-04 12:04 UTC, BlueGlassBlock commented
所有版本均可正常构建了

cc @zhsj

2023-04-11 07:28 UTC, BlueGlassBlock commented
https://github.com/BlueGlassBlock/python-docs-zh-cn/actions/runs/4657587611

应该是18小时前有人提交了包含语法错误的翻译导致之后的构建错误

2023-04-12 13:19 UTC, BlueGlassBlock commented
> 我看到现在311正常，其他的有报错

已经定位到有问题的依赖

https://github.com/pygments/pygments/issues/2407

2023-05-13 08:50 UTC, Jiuh-star commented
> > 我看到现在311正常，其他的有报错
> 
> 已经定位到有问题的依赖
> 
> [pygments/pygments#2407](https://github.com/pygments/pygments/issues/2407)

Pygments 2.15.1 似乎解决了该问题，请问有最新的进展吗？

2023-05-13 08:59 UTC, BlueGlassBlock commented
> Pygments 2.15.1 似乎解决了该问题，请问有最新的进展吗？

[CI 页](https://github.com/BlueGlassBlock/python-docs-zh-cn/actions) 表明除了 Python 3.10 以外的 CI 构建均已恢复正常，[3.10 的翻译](https://github.com/BlueGlassBlock/python-docs-zh-cn/actions/runs/4965950711/jobs/8887095020)经过修正后应该就可以正常构建了。

2023-05-13 11:34 UTC, Jiuh-star requested changes

2023-05-13 11:53 UTC, Jiuh-star commented
> 官方客户端的问题是非常非常慢，很难在一小时内同步完所有版本。
> 
> 现在新版本有改善了吗？(好像拿Go重新了，可能效率没问题了）。
> 
> 你可以在你自己的repo里跑一下，贴一下结果吗？

Transifex CLI 用 Go 重构之后速度没有明显改善，平均也需要 1~2 分钟左右的时间，花费的总时间上与旧版本相当，但使用新版本确实使得代码更好维护了 ( 虽然能跑就行... )。

目前一个 Workflow 平均需要 8~15 分钟左右，时间大部分花费在 Sphinx 的构建上，更换 Sphinx 客户端无伤大雅。

<details>

![Workflows](https://github.com/python/python-docs-zh-cn/assets/47910035/e423857e-a2b1-4c4d-be51-6a93e6a6aa71)

![The output of the update.sh in a workflow](https://github.com/python/python-docs-zh-cn/assets/47910035/3edadbb5-d8c2-4402-a2a0-9d419532179a)

</details>

依赖问题已经解决，我认为这个 PR 可以合并。

2023-05-13 12:13 UTC, Jiuh-star commented on README.rst
> +   * - `3.11 <https://github.com/python/python-docs-zh-cn/tree/3.10>`_
是否应该改为
```rst
* - `3.11 <https://github.com/python/python-docs-zh-cn/tree/3.11>`_
```

2023-05-13 12:16 UTC, Jiuh-star requested changes
`README.rst` 中可能存在的 icon 显示问题

2023-05-13 12:16 UTC, Jiuh-star commented on README.rst
> +   * - `3.11 <https://github.com/python/python-docs-zh-cn/tree/3.10>`_
是否应该改为
```rst
   * - `3.11 <https://github.com/python/python-docs-zh-cn/tree/3.11>`_
```

2023-05-13 12:16 UTC, Jiuh-star commented on README.rst
> +     - .. image:: https://img.shields.io/badge/dynamic/json.svg?label=zh_CN&query=%24.zh_CN&url=http://gce.zhsj.me/python/310
是否应该改为
```rst
    - .. image:: https://img.shields.io/badge/dynamic/json.svg?label=zh_CN&query=%24.zh_CN&url=http://gce.zhsj.me/python/311
```

2023-05-13 13:30 UTC, BlueGlassBlock commented on README.rst
> +     - .. image:: https://img.shields.io/badge/dynamic/json.svg?label=zh_CN&query=%24.zh_CN&url=http://gce.zhsj.me/python/310
似乎 zhsj 的源站挂了，不过确实应该修一下

2023-05-13 13:38 UTC, Jiuh-star approved these changes

2023-05-28 18:36 UTC, rffontenelle commented
3.12 now available in default project (python-newest). Consider branvhing 3.11, but also enabling 3.12 as default version.

2023-05-29 05:47 UTC, BlueGlassBlock commented
> 3.12 now available in default project (python-newest). Consider branching 3.11, but also enabling 3.12 as default version.

Thanks for elaborating that, I have added corresponding workflow file. I'll sync 3.11 configuration file with `python-311` on my branch when translation migration completes.

2023-06-15 11:40 UTC, BlueGlassBlock commented
在我的 repo 更新 `3.11` 了分支以使用 transifex 的 `python-311` 项目，[CI 全部通过](https://github.com/BlueGlassBlock/python-docs-zh-cn/actions)，我认为这个 PR 已经完备了。

再次 ping @zhsj 请求 review

不过在 merge 这个 PR 前，需要从[我的 repo](https://github.com/BlueGlassBlock/python-docs-zh-cn) 同步 `3.11` 与 `3.12` 两个分支到这里。

2023-06-29 13:25 UTC, BlueGlassBlock commented
在 Python 3.7 EOL 后 transifex 上的 `python-37` 翻译已存档，停止接收翻译贡献。但因为 repo 的 CI 已经长时间停止运作，我们仍需最后拉取更改后再删除对应的 CI 配置。

同时，我注意到翻译项目的协调员很长时间没有对这个 PR 进行跟进，鉴于 Python 3.12 已经进入 beta 阶段，在此再次 ping 一下 @zhsj

2023-06-29 13:33 UTC, rffontenelle commented
Maybe the current maintainer is unavailable and a new one is needed? If so, consider bringing this up in the in the [translation mailing list](https://mail.python.org/mailman3/lists/translation.python.org/).

2023-08-03 07:08 UTC, merged